### ISSUE TITLE
train code running error

### ISSUE THREAD

**Issue by meongeun** [XingliangJin/Fine-Style#1]
File "/home/user/Fine-Style/probe/../networks.py", line 290, in forward
assert(x.size(0) == y.size(0)) 
AttributeError: 'int' object has no attribute 'size'

Is the training code working well? I get an error like this, also the size of x should be [n.k.m], but the shape of x is [n,k].

**Comment by XingliangJin** [comment]
There is indeed a bug in the training code. Please use `python train.py` instead of `python train.py --name experiment_name`, and change the name in the config.py to set your experiment_name. We are working on this bug and will fix it soon.

**Comment by meongeun** [comment]
Okay. Please let me know when you fix the bug.

**Comment by XingliangJin** [comment]
I mean you can run the training code by using the command `python train.py`. Additionally, you'll need to change the experiment name to your preference at line 16 in `config.py`.

**Comment by meongeun** [comment]
it's working after changing the config file. thank you 👍
