### ISSUE TITLE
xia.npz file

### ISSUE THREAD

**Issue by SeuGuoTong** [XingliangJin/Fine-Style#3]
Can you explain the generation of the xia.npz file? I would greatly appreciate your response

**Comment by XingliangJin** [comment]
xia.npz is generated through [data_proc/export_train.py](https://github.com/XingliangJin/Fine-Style/tree/master/data_proc/export_train.py). It mainly includ some data slicing, etc. You can check it for more details.

**Comment by SeuGuoTong** [comment]
Thank you very much for your answer! I would like to know more about it/ The process of obtaining data/xia_norms', especially how to calculate Mean and Std for 3D data. Is that so?

**Comment by SeuGuoTong** [comment]
Thank you very much for your answer! I would like to know more about it/ The process of obtaining data/xia_norms', especially how to calculate Mean and Std for 3D data. Is that so?

concatenated_data = np.concatenate(data_list, axis=0)﻿
Mean = concatenated_data.mean(axis=(0, 1))
Std = concatenated_data.std(axis=(0, 1))

**Comment by XingliangJin** [comment]
You can check the code for calculating Mean and Std in here： https://github.com/XingliangJin/Fine-Style/blob/9396a50fc7f1357419d8b034935ee578d24d357f/data_loader.py#L41-L65
