### ISSUE TITLE
rotated data(content input) and 3D data(style3d input)

### ISSUE THREAD

**Issue by SeuGuoTong** [XingliangJin/Fine-Style#5]
May I know the specific difference between rotated data and 3D data? Is the rotation data specifically a quaternion?

**Comment by XingliangJin** [comment]
Rotated data is processed from 3D pose data to better represent motion information, whereas style uses 3D pose data to better represent style. You can refer to the original papers [Deep-Motion-Editing](https://arxiv.org/abs/2005.05751) and [Holden et al. [2016]](http://theorangeduck.com/page/deep-learning-framework-character-motion-synthesis-and-editing) for more detail about the data format.

**Comment by SeuGuoTong** [comment]
Thank you very much for your reply!
